name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t noc-cnn-accelerator .
      
    - name: Test Baseline Design
      run: docker run --rm noc-cnn-accelerator bash -c "cd src/baseline && make cat"
      
    - name: Test Optimized Design
      run: docker run --rm noc-cnn-accelerator bash -c "cd src/optimized && make cat"
